
stages:         
  - deploy

build-containers:
  tags:
  - docker
  - monstre       
  stage: build
  image: docker:latest
  only:
  - main
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli --break-system-packages
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - aws --version
  script:
    - cd /home/rodenewadmin
    - git clone https://${{ secrets.PAT }}@github.com/guigolab/bgp-configs.git 
    - rsync -av --delete /home/rodenewadmin/bgp-configs/biogenome-portal-ebp/ /home/rodenewadmin/biogenome-portal-ebp/
    - cd /home/rodenewadmin/biogenome-portal-ebp/
    - docker compose down
    - docker compose pull
    - docker compose up -d
    - rsync -av --delete /home/rodenewadmin/bgp-configs/biogenome-portal-erga/ /home/rodenewadmin/biogenome-portal-erga/
    - cd /home/rodenewadmin/biogenome-portal-erga/
    - docker compose down
    - docker compose pull
    - docker compose up -d
    - rsync -av --delete /home/rodenewadmin/bgp-configs/biogenome-portal-lichenoteca/ /home/rodenewadmin/biogenome-portal-lichenoteca/
    - cd /home/rodenewadmin/biogenome-portal-lichenoteca/
    - docker compose down
    - docker compose pull
    - docker compose up -d
    - rm -rf /home/rodenewadmin/bgp-configs