variables:
    APP_NAME_FRONT: $APP_NAME_FRONT
    APP_NAME_CRON: biogenome_cronjob
    APP_NAME_BACK: biogenome_back
    APP_TO_DEPLOY: $APP_TO_DEPLOY


stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-containers:
  tags:
  - docker
  - monstre       
  stage: build
  image: docker:latest
  only:
    - manual
    - main
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - cat $FRONT_CONFIGS > ./biogenome-client/config.json
    - cat $CRON_CONFIGS > ./cronjobs/crontab
  script:
    - docker build --build-arg CESIUM_TOKEN="$CESIUM_TOKEN" --build-arg BASE_PATH="$BASE_PATH" --build-arg ROOT_NODE="$ROOT_NODE" --build-arg PROJECT_ACCESSION="$PROJECT_ACCESSION" -t gitlab.linux.crg.es:5005/monstre/biogenome-portal/$APP_NAME_FRONT ./biogenome-client
    - docker push gitlab.linux.crg.es:5005/monstre/biogenome-portal/$APP_NAME_FRONT
    - docker build -t gitlab.linux.crg.es:5005/monstre/biogenome-portal/$APP_NAME_BACK ./server
    - docker push gitlab.linux.crg.es:5005/monstre/biogenome-portal/$APP_NAME_BACK
    - docker build -t gitlab.linux.crg.es:5005/monstre/biogenome-portal/$APP_NAME_CRON ./cronjobs
    - docker push gitlab.linux.crg.es:5005/monstre/biogenome-portal/$APP_NAME_CRON

deploy-app:
  stage: deploy
  trigger: monstre/rg-web