version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx-entrypoint.sh:/nginx-entrypoint.sh
      - cms:/usr/share/nginx/html/cms
      - genome-browser:/usr/share/nginx/html/genome-browser
      - portal:/usr/share/nginx/html/portal
    environment:
      - API_PATH=/ # Set to "/" for root or any subpath
    entrypoint: ["/bin/sh", "/nginx-entrypoint.sh"]
    ports:
      - "80:80"

  cms:
    build:
      context: ./cms
    container_name: cms
    volumes:
      - cms:/usr/share/nginx/html/cms

  genome-browser:
    build:
      context: ./genome-browser
    container_name: genome-browser
    volumes:
      - genome-browser:/usr/share/nginx/html/genome-browser

  portal:
    build:
      context: ./portal
    container_name: portal
    volumes:
      - portal:/usr/share/nginx/html/portal


  biogenome_mongo:
    image: mongo:6.0
    container_name: "${DB_HOST}"
    env_file:
      - .env
    volumes:
     - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
     - /home/cbp-data:/data/db
    ports:
      - 27015:${DB_PORT}

  biogenome_server:
    build: ./server
    container_name: "biogenome_server"
    restart: always
    volumes:
      - ./server:/server
      - ${ANNOTATIONS_PATH}:/annotations_data
    env_file:
      - .env
    depends_on:
      - redis
  celery:
    build: ./server
    command: celery --app app.celery_app worker --loglevel=info --autoscale=2,1
    restart: always
    volumes:
      - ./server:/server
    env_file:
      - .env
    depends_on:
      - biogenome_server
      - biogenome_mongo
      - redis

  redis:
    image: "redis:alpine"

volumes:
  cms:
  genome-browser:
  portal:
  app:
  mongodb-data:
  node_modules:

