version: '3'

services:

  biogenome_mongo_dev_env:
    image: mongo:6.0
    container_name: "${DB_HOST}"
    env_file:
      - .env
    volumes:
     - /home/emilior/cbp-data:/data/db
     - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh

    ports:
      - 27015:${DB_PORT}

  biogenome_server:
    build: ./server
    container_name: "biogenome_server"
    restart: always
    volumes:
      - ./server:/server
      - /home/emilior/cbp-annotations-data:/annotations_data

    env_file:
      - .env
    ports:
     - 5000:5000
    depends_on:
      - redis

  # biogenome_cron:
  #   build: ./cronjobs
  #   container_name: biogenome_cron
  #   env_file:
  #     - .env
  # biogenome_cron:
  #   build: ./cronjobs
  #   container_name: biogenome_cron
  #   env_file:
  #     - .env

  biogenome_nginx:
    build:
      context: ./biogenome-client
      dockerfile: Dockerfile
      args:
        BASE_PATH: ${BASE_PATH}
    container_name: "biogenome_nginx"
    restart: always
    volumes:
      - ./biogenome-client:/biogenome-client
      - node_modules:/biogenome-client/node_modules
    env_file:
      - .env
    ports:
        - "91:${API_PORT}"


  celery:
    build: ./server
    command: celery --app app.celery_app worker --loglevel=info --autoscale=2,1
    restart: always
    volumes:
      - ./server:/server
    env_file:
      - .env
    depends_on:
      - biogenome_server
      - biogenome_mongo_dev_env
      - redis

  # biogenome_cron:
  #   build: ./cronjobs
  #   container_name: biogenome_cron
  #   env_file:
  #     - .env

  # biogenome_nginx:
  #   build:
  #     context: ./biogenome-client
  #     dockerfile: Dockerfile
  #     args:
  #       - ROOT_NODE=$ROOT_NODE
  #       - CESIUM_TOKEN=$CESIUM_TOKEN
  #       - BASE_PATH=$BASE_PATH
  #   container_name: "biogenome_nginx"
  #   restart: always
  #   volumes:
  #     - node_modules:/biogenome-client/node_modules
  #   environment:
  #     - API_PORT=${API_PORT}
  #     - API_HOST=${API_HOST}
  #     - BASE_PATH=${BASE_PATH}
  #   ports:
  #       - "91:${API_PORT}"

  # celery:
  #   build: ./server
  #   command: celery --app app.celery_app worker --loglevel=info --autoscale=1,1 --max-tasks-per-child=1
  #   restart: always
  #   volumes:
  #     - ${ANNOTATIONS_PATH}:/annotations_data
  #   env_file:
  #     - .env
  #   depends_on:
  #     - biogenome_server
  #     - biogenome_db
  #     - redis

  redis:
    image: "redis:alpine"

volumes:
  app:
  node_modules:
