version: '3'

services:

  biogenome_mongo:
    image: mongo:latest
    container_name: "${DB_DEV_HOST}"
    env_file:
      - .env
    volumes:
     - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
     - mongodb-data:${MONGODB_DATA_DIR}
    ports:
      - "27015:${DB_PORT}"
  
  biogenome_server:
    build: ./server
    container_name: "biogenome_server"
    restart: always
    volumes:
      - ./server:/server
    env_file: 
      - .env

  biogenome_cron:
    build: ./cronjobs
    container_name: biogenome_cron
    env_file:
      - .env

  biogenome_nginx:
    build: 
      context: ./biogenome-client
      dockerfile: Dockerfile
      args:
        - ROOT_NODE=$ROOT_NODE
        - PROJECT_ACCESSION=$PROJECT_ACCESSION
    container_name: "biogenome_nginx"
    restart: always
    volumes:
      - ./biogenome-client:/biogenome-client
      - node_modules:/biogenome-client/node_modules
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
    ports:
        - "91:${API_PORT}"   

volumes:
  app:
  mongodb-data:
  node_modules:
