version: '3'

services:
  biogenome_server:
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    container_name: "biogenome_server"
    restart: always
    environment: 
      - APP_NAME=PORTAL
    expose:
      - "80"
    volumes:
      - ./server:/server
      - ./tmp:/tmp
    env_file: 
      - .env

  biogenome_nginx:
    build: ./client
    container_name: "biogenome_nginx"
    restart: always
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules
      - ./tmp:/tmp
    ports:
        - "91:80"
    environment:
        - API_HOST=biogenome_server
        - API_PORT=80
        
  biogenome_mongo:
    image: mongo:latest
    container_name: "biogenome_mongo"
    command: mongod --port 27015
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: flask_db
      MONGODB_DATA_DIR: /var/lib/mongodb-data
      MONDODB_LOG_DIR: /dev/null
    volumes:
     - mongodb-data:/var/lib/mongodb-data
    ports:
      - "27015:27015"

volumes:
  app:
  mongodb-data:
  node_modules:
