version: '3'

services:
  biogenome_server:
    build: ./server
    container_name: "biogenome_server"
    restart: always
    volumes:
      - ./server:/server
    env_file: 
      - .env
    networks:
      - default
      - biogenome-network
      
  biogenome_nginx:
    build: 
      context: ./client
      dockerfile: Dockerfile
      args:
        - ROOT_NODE=$ROOT_NODE
        - PROJECT_ACCESSION=$PROJECT_ACCESSION
    container_name: "biogenome_nginx"
    restart: always
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
    ports:
        - "91:${API_PORT}"   
networks:
  default:
    driver: bridge
  biogenome-network:
    external:
      name: biogenome-network     
      
volumes:
  app:
  node_modules:
