version: '3'

services:

  bioG_mongo:
    image: mongo:5.0.3
    container_name: "${DB_DEV_HOST}"
    env_file:
      - .env
    volumes:
     - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    #  - ./mongo-restore.sh:/docker-entrypoint-initdb.d/mongo-restore.sh
    #  - ./db-dump:/db-dump
     - mongodb-data:${MONGODB_DATA_DIR}
    ports:
      - "27015:${DB_PORT}"

  # mongo-backup:
  #   image: tarator/mongodump:5.0
  #   restart: always
  #   links:
  #     - biogenome_mongo
  #   depends_on:
  #     - biogenome_mongo ## link to mongo service name
  #   volumes:
  #     - ./mongo_backup:/backup:rw
  #   environment:
  #     - MONGO_HOST=biogenome_mongo
  #     - MONGO_PORT=27017
  #     - BACKUP_CRON_TIME=* * * * *
  #     - KEEP_DAYS=14

  biogenome_server:
    build: ./server
    container_name: "biogenome_server"
    restart: always
    volumes:
      - ./server:/server
    env_file:
      - .env

  # biogenome_cron:
  #   build: ./cronjobs
  #   container_name: biogenome_cron
  #   env_file:
  #     - .env

  biogenome_nginx:
    build:
      context: ./biogenome-client
      dockerfile: Dockerfile
      args:
        - ROOT_NODE=$ROOT_NODE
        - PROJECT_ACCESSION=$PROJECT_ACCESSION
        - CESIUM_TOKEN=$CESIUM_TOKEN
    container_name: "biogenome_nginx"
    restart: always
    volumes:
      - ./biogenome-client:/biogenome-client
      - node_modules:/biogenome-client/node_modules
      - ./genome-browser-data-example:/var/www/statics
    environment:
      - API_PORT=${API_PORT}
      - API_HOST=${API_HOST}
    ports:
        - "91:${API_PORT}"

volumes:
  app:
  mongodb-data:
  node_modules:
