/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    BlockUI: typeof import('primevue/blockui')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Chip: typeof import('primevue/chip')['default']
    Column: typeof import('primevue/column')['default']
    Columns: typeof import('./src/components/Columns.vue')['default']
    D3HyperTree: typeof import('./src/components/D3HyperTree.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    ExportTSV: typeof import('./src/components/ExportTSV.vue')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    Filters: typeof import('./src/components/Filters.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Fluid: typeof import('primevue/fluid')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Items: typeof import('./src/components/Items.vue')['default']
    MapCard: typeof import('./src/components/MapCard.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    Message: typeof import('primevue/message')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavBarLogo: typeof import('./src/components/NavBarLogo.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    Popover: typeof import('primevue/popover')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    TaxonInfoPopover: typeof import('./src/components/TaxonInfoPopover.vue')['default']
    TaxonSummary: typeof import('./src/components/TaxonSummary.vue')['default']
    TaxonWikiSummary: typeof import('./src/components/TaxonWikiSummary.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
