name: Trigger Cronjob build

on:
    push:
        branches: ['main']
        paths: ['cronjobs/**']

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow in private repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ secrets.CONFIG_REPO }}
          event-type: cronjob-build