name: Trigger Private Repo Workflow

on:
  push:
    branches:
      - main


jobs:
  trigger-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger workflow in private repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ secrets.CONFIG_REPO }}
          event-type: full-deploy